# Generated by Django 4.0.4 on 2022-05-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lattice_app', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=1000)),
                ('desc', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=100)),
                ('features', models.CharField(max_length=1000)),
            ],
        ),
    ]
